-- Migration Patch 16: Comprehensive Philippine LGU E-Services Catalog
-- Populates lgu_services with all 28 authentic Philippine Local Government services
-- across Civil Registrar, BPLO, Barangay, Treasurer, Assessor, MPDO, OBO, Health, MSWDO

-- Clean existing seeded records for liliw-laguna and nagcarlan-laguna
DELETE FROM lgu_services WHERE lgu_id IN ('liliw-laguna', 'nagcarlan-laguna');

INSERT INTO lgu_services (lgu_id, office_name, name, description, requirements, fee_note, processing_time, sort_order)
VALUES
  -- ===== LILIW, LAGUNA =====
  -- BPLO / BOSS
  ('liliw-laguna', 'BPLO', 'New Business Permit (Mayor''s Permit)', 'Application for a new Mayor''s/Business Permit to legally operate a commercial establishment.', '["DTI / SEC / CDA Registration Certificate","Barangay Business Clearance with Official Receipt","Contract of Lease or Land Title / Tax Dec","Locational / Zoning Clearance (MPDO)","Fire Safety Evaluation Clearance (BFP)","Sanitary Permit to Operate (Health Office)","Sketch / Vicinity Map of Location"]'::jsonb, 'Assessed by BPLO — pay at Municipal Treasurer', '3-5 working days', 1),
  ('liliw-laguna', 'BPLO', 'Business Permit Renewal', 'Annual renewal of existing business permit to operate (filed every January 1-20).', '["Previous Year Mayor''s Permit & Official Receipt","Current Year Barangay Business Clearance","Audited Financial Statement (AFS) or BIR Form 1701/1702 / Gross Sales Sworn Statement","Current Year Fire Safety Inspection Certificate","Current Year Sanitary Permit & Health Cards"]'::jsonb, 'Assessed based on gross sales — pay at Municipal Treasurer', '1-3 working days', 2),
  ('liliw-laguna', 'BPLO', 'Occupational / Work Permit', 'Official Mayor''s permit for individuals practicing a trade or employed within the municipality.', '["One (1) Valid Government ID","Food Handler / Worker Health Card (Health Office)","Police Clearance or NBI Clearance","Community Tax Certificate (Cedula)"]'::jsonb, '₱100.00 – ₱200.00 — pay at Municipal Treasurer', '1-2 working days', 3),

  -- Civil Registrar
  ('liliw-laguna', 'Civil Registrar', 'Certificate of Live Birth (Timely Registration)', 'Registration of newborn birth within 30 days of delivery.', '["Duly accomplished COLB Form 102 signed by attending physician/midwife","Valid IDs of parents","Marriage Certificate of parents (if married)","6 copies Notarized AUSF & AAP (if parents unmarried)"]'::jsonb, 'Free / No charge for basic timely registration', '1-2 working days', 4),
  ('liliw-laguna', 'Civil Registrar', 'Late Birth Registration (>30 Days)', 'Registration of birth beyond 30 days of occurrence pursuant to Act 3753.', '["PSA Negative Certificate of Live Birth","Accomplished Delayed Registration Form & Notarized Affidavit of Delayed Registration","Valid IDs of parents and applicant","At least TWO (2) supporting documentary proofs (Baptismal, Form 137, Immunization card, Voter''s cert, SSS)"]'::jsonb, '₱200.00 (Late filing + posting fee) — pay at Municipal Treasurer', '10-12 working days (10-day posting period)', 5),
  ('liliw-laguna', 'Civil Registrar', 'Certified True Copy of Civil Registry Document', 'Official certified true copy or extract of Birth, Marriage, or Death certificate on file in the local registry.', '["One (1) Valid Government ID of requester","Accomplished Request Slip (Book/Page/Registry No.)","Notarized Authorization Letter / SPA (if representative)"]'::jsonb, '₱100.00 per copy — pay at Civil Registrar / Treasurer', '1-2 working days', 6),
  ('liliw-laguna', 'Civil Registrar', 'Marriage License Application', 'Application for marriage license required prior to solemnization of marriage.', '["PSA Birth Certificates of both parties","PSA CENOMAR valid within 6 months","Certificate of Pre-Marriage Counseling (PMOC) from CSWDO & Health Office","Community Tax Certificate (Cedula) of both parties","Valid IDs of both parties","Parental Consent (18-20) / Advice (21-24) if applicable"]'::jsonb, '₱200.00 – ₱300.00 — pay at Municipal Treasurer', '10-12 working days (10-day posting period)', 7),
  ('liliw-laguna', 'Civil Registrar', 'Certificate of Death (Timely Registration)', 'Registration of death within 30 days of occurrence.', '["Triplicate Certificate of Death (Form 103) signed by attending physician / MHO","Valid ID of informant / nearest surviving kin","Barangay Death Certificate or Hospital Medical Record"]'::jsonb, 'Free for timely registration', 'Same day / 1 working day', 8),
  ('liliw-laguna', 'Civil Registrar', 'Legitimation of Child (R.A. 9858)', 'Legal process legitimizing children born out of wedlock upon subsequent marriage of biological parents.', '["Child''s Certified Certificate of Live Birth (Local & PSA)","Parents'' Certified Marriage Contract (Local & PSA)","Joint Notarized Affidavit of Legitimation","PSA CENOMAR of both parents","Valid IDs of both parents"]'::jsonb, '₱250.00 — pay at Municipal Treasurer', '3-5 working days', 9),
  ('liliw-laguna', 'Civil Registrar', 'Correction of Clerical Error (R.A. 9048 / R.A. 10172)', 'Administrative petition to correct typographical or clerical errors in birth, marriage, or death records.', '["Verified Petition Form under oath","PSA Security Paper (SECPA) copy of erroneous document","Earliest school record (Form 137 / Diploma)","Baptismal Certificate / Early church records","NBI or Police Clearance","Two (2) supporting public/private IDs/records with correct info"]'::jsonb, '₱1,000.00 (RA 9048) / ₱3,000.00 (RA 10172) — pay at Municipal Treasurer', '15-20 working days', 10),

  -- Barangay Affairs
  ('liliw-laguna', 'Barangay Affairs', 'Barangay Clearance (Employment / General)', 'Barangay certification verifying that the resident has no derogatory record in the community.', '["One (1) Valid Photo ID","Community Tax Certificate (Cedula) for current year","Proof of residency (Utility bill / attestation)"]'::jsonb, '₱50.00 – ₱100.00 (Free for First-Time Jobseekers under RA 11261)', 'Same day / 1 working day', 11),
  ('liliw-laguna', 'Barangay Affairs', 'Barangay Certificate of Residency', 'Certification of bona fide residency within the territorial jurisdiction of the barangay.', '["One (1) Valid ID with current address","Proof of residency (Utility bill, lease contract, or homeowner certification)"]'::jsonb, '₱50.00 — pay at Barangay Hall', 'Same day', 12),
  ('liliw-laguna', 'Barangay Affairs', 'Barangay Certificate of Indigency', 'Certification of indigent status for medical, financial, educational, or legal assistance.', '["One (1) Valid ID of applicant","Proof of assistance need (Hospital bill, prescription, enrollment form, or PAO referral)"]'::jsonb, 'Free / No charge', 'Same day', 13),
  ('liliw-laguna', 'Barangay Affairs', 'Barangay Business Clearance', 'Barangay-level commercial clearance required prior to Mayor''s Permit application.', '["DTI / SEC / CDA Registration Certificate","Contract of Lease or Land Title / Tax Dec","Community Tax Certificate (Cedula) of owner","Valid ID of business owner"]'::jsonb, '₱200.00 – ₱500.00 (per barangay ordinance)', '1-2 working days', 14),

  -- Municipal Treasurer
  ('liliw-laguna', 'Treasurer''s Office', 'Community Tax Certificate (Cedula)', 'Annual community tax certificate issued to residents and corporations upon assessment of gross income.', '["One (1) Valid Government ID","Proof of income / BIR 2316 / Payslip (for employed)"]'::jsonb, '₱5.00 basic + ₱1.00 per ₱1,000 gross earnings — pay at Treasurer', '15-30 minutes / Same day', 15),
  ('liliw-laguna', 'Treasurer''s Office', 'Real Property Tax (RPT / Land Tax) Payment', 'Annual payment of ad valorem real property taxes on land, buildings, and improvements.', '["Previous Year Real Property Tax Official Receipt (OR)","Copy of Tax Declaration (TDN) from Assessor''s Office","Valid ID of owner or representative"]'::jsonb, '1% Basic RPT + 1% SEF of assessed property value', 'Same day / 1 working day', 16),
  ('liliw-laguna', 'Treasurer''s Office', 'Real Property Tax Clearance', 'Certification showing all real property tax obligations on a declared property have been fully settled.', '["Official Receipts of full RPT payment for current year","Copy of Tax Declaration","Valid ID of applicant"]'::jsonb, '₱50.00 – ₱100.00 clearance fee — pay at Treasurer', '1 working day / Same day', 17),
  ('liliw-laguna', 'Treasurer''s Office', 'Transfer Tax Payment & Certification', 'Tax on the sale, donation, or transfer of real property ownership.', '["Notarized Deed of Absolute Sale, Donation, or Extrajudicial Settlement","BIR Certificate Authorizing Registration (CAR) & Tax Receipts","Certified True Copy of Land Title (TCT / CCT)","Updated Tax Declaration and RPT Tax Clearance"]'::jsonb, '0.5% – 0.75% of selling price or fair market value', '1-2 working days', 18),

  -- Assessor''s Office
  ('liliw-laguna', 'Assessor''s Office', 'Transfer / Issuance of Tax Declaration', 'Updating the official assessment record and issuing a new Tax Declaration under the buyer/transferee name.', '["Registered Deed of Conveyance stamped by Registry of Deeds","New Transfer Certificate of Title (TCT) under buyer''s name","BIR Certificate Authorizing Registration (CAR)","Transfer Tax Official Receipt (Treasurer)","Updated Real Property Tax Clearance (Treasurer)"]'::jsonb, '₱100.00 – ₱200.00 transfer & inspection fee — pay at Treasurer', '3-5 working days', 19),
  ('liliw-laguna', 'Assessor''s Office', 'Certified True Copy of Tax Declaration', 'Official certified copy of a property''s current Tax Declaration record.', '["One (1) Valid Government ID of owner / requester","Tax Declaration Number or Property Identification Number (PIN)","Authorization Letter / SPA (if representative)"]'::jsonb, '₱50.00 – ₱100.00 per copy — pay at Treasurer', 'Same day / 1 working day', 20),

  -- MPDO (Planning & Zoning)
  ('liliw-laguna', 'Municipal Planning and Development Office', 'Locational / Zoning Clearance', 'Certification of compliance with municipal zoning ordinances and Comprehensive Land Use Plan (CLUP).', '["Duly accomplished Locational Clearance Application Form","Certified True Copy of Land Title (TCT) or Contract of Lease","Vicinity Map and Site Development Plan signed & sealed by licensed Architect/Civil Engineer","Barangay Clearance for Construction / Business","Current Year Real Property Tax Official Receipt"]'::jsonb, 'Assessed per square meter / project cost schedule', '3-5 working days', 21),

  -- OBO (Building & Engineering)
  ('liliw-laguna', 'Office of the Building Official (OBO)', 'Building Permit (New Construction / Renovation)', 'Official statutory permit to erect, alter, repair, or demolish structures under P.D. 1096.', '["Accomplished Unified Building Permit Application Forms","5 sets of complete Architectural, Structural, Electrical, Sanitary, and Mechanical Plans (signed & sealed by PRC licensed professionals with valid PTR)","Certified True Copy of Land Title (TCT) & Tax Declaration","Structural Design Computations (for buildings >2 storeys)","Bill of Materials and Cost Estimates / Specifications","Locational / Zoning Clearance (MPDO)","Fire Safety Evaluation Clearance (FSEC from BFP)","Barangay Construction Clearance"]'::jsonb, 'Assessed per NBCP Schedule of Fees — pay at Treasurer', '7-15 working days', 22),
  ('liliw-laguna', 'Office of the Building Official (OBO)', 'Certificate of Occupancy', 'Authorization that a completed building structure complies with all safety codes and is fit for occupancy.', '["Accomplished Certificate of Completion Forms signed & sealed by supervising engineer","Approved Building Permit & Official Receipts","As-Built Plans (if deviations occurred)","Fire Safety Inspection Certificate for Occupancy (BFP)","Construction Logbook signed by engineer in-charge"]'::jsonb, 'Assessed based on floor area & occupancy category', '5-7 working days', 23),

  -- Municipal Health Office
  ('liliw-laguna', 'Health Office', 'Sanitary Permit to Operate (Establishments)', 'Health and sanitation clearance required for commercial, food, and industrial establishments under P.D. 856.', '["Business Permit Application / Registration details","Microbiological & Physico-Chemical Water Analysis Test Results (from DOH-accredited lab)","Employee Health Certificates (Health Cards) of all staff","Pest Control Management Certification"]'::jsonb, 'Assessed by Health Office — pay at Municipal Treasurer', '2-3 working days', 24),
  ('liliw-laguna', 'Health Office', 'Food Handler''s Health Certificate (Health Card)', 'Individual medical certificate certifying that food service and personal care workers are free from communicable diseases.', '["Chest X-Ray result (Normal / Clear) within last 6 months","Routine Stool Examination / Fecalysis result (Negative)","Routine Urinalysis examination result","One (1) 1x1 or 2x2 ID picture"]'::jsonb, '₱50.00 – ₱100.00 — pay at Health Office / Treasurer', '1 working day (after lab submissions)', 25),

  -- MSWDO & OSCA
  ('liliw-laguna', 'MSWDO', 'Crisis Assistance (AICS / Financial & Medical Aid)', 'Emergency financial, hospitalization, medication, burial, or transportation assistance for indigent residents in crisis.', '["Barangay Certificate of Indigency for Financial/Medical Assistance","Valid Government ID of beneficiary and claimant","Medical Abstract / Itemized Hospital Bill / Official Prescriptions (for medical aid)","Certified Death Certificate & Funeral Contract / Statement of Account (for burial aid)"]'::jsonb, 'Free / No charge', '1-2 working days', 26),
  ('liliw-laguna', 'MSWDO', 'Senior Citizen ID Registration & Booklet', 'Issuance of Senior Citizen National ID and purchase booklet for residents 60 years old and above under R.A. 9994.', '["PSA / Local Birth Certificate proving age 60+ (or valid Passport / Voter''s ID)","Barangay Certificate of Residency","Two (2) copies 1x1 recent ID photos"]'::jsonb, 'Free / No charge', 'Same day / 1-2 working days', 27),
  ('liliw-laguna', 'MSWDO', 'Person with Disability (PWD) ID Application', 'Official identification card and purchase booklet for persons with permanent disabilities under R.A. 10754.', '["Medical Certificate / Disability Assessment Form signed by licensed physician","Barangay Certificate of Residency","Two (2) copies 1x1 recent ID photos","One (1) Valid ID of applicant or parent/guardian"]'::jsonb, 'Free / No charge', '1-3 working days', 28),

  -- ===== NAGCARLAN, LAGUNA =====
  ('nagcarlan-laguna', 'BPLO', 'New Business Permit (Mayor''s Permit)', 'Application for a new Mayor''s/Business Permit to legally operate a commercial establishment.', '["DTI / SEC / CDA Registration Certificate","Barangay Business Clearance with Official Receipt","Contract of Lease or Land Title / Tax Dec","Locational / Zoning Clearance (MPDO)","Fire Safety Evaluation Clearance (BFP)","Sanitary Permit to Operate (Health Office)","Sketch / Vicinity Map of Location"]'::jsonb, 'Assessed by BPLO — pay at Municipal Treasurer', '3-5 working days', 1),
  ('nagcarlan-laguna', 'BPLO', 'Business Permit Renewal', 'Annual renewal of existing business permit to operate (filed every January 1-20).', '["Previous Year Mayor''s Permit & Official Receipt","Current Year Barangay Business Clearance","Audited Financial Statement (AFS) or BIR Form 1701/1702 / Gross Sales Sworn Statement","Current Year Fire Safety Inspection Certificate","Current Year Sanitary Permit & Health Cards"]'::jsonb, 'Assessed based on gross sales — pay at Municipal Treasurer', '1-3 working days', 2),
  ('nagcarlan-laguna', 'BPLO', 'Occupational / Work Permit', 'Official Mayor''s permit for individuals practicing a trade or employed within the municipality.', '["One (1) Valid Government ID","Food Handler / Worker Health Card (Health Office)","Police Clearance or NBI Clearance","Community Tax Certificate (Cedula)"]'::jsonb, '₱100.00 – ₱200.00 — pay at Municipal Treasurer', '1-2 working days', 3),
  ('nagcarlan-laguna', 'Civil Registrar', 'Certificate of Live Birth (Timely Registration)', 'Registration of newborn birth within 30 days of delivery.', '["Duly accomplished COLB Form 102 signed by attending physician/midwife","Valid IDs of parents","Marriage Certificate of parents (if married)","6 copies Notarized AUSF & AAP (if parents unmarried)"]'::jsonb, 'Free / No charge for basic timely registration', '1-2 working days', 4),
  ('nagcarlan-laguna', 'Civil Registrar', 'Late Birth Registration (>30 Days)', 'Registration of birth beyond 30 days of occurrence pursuant to Act 3753.', '["PSA Negative Certificate of Live Birth","Accomplished Delayed Registration Form & Notarized Affidavit of Delayed Registration","Valid IDs of parents and applicant","At least TWO (2) supporting documentary proofs (Baptismal, Form 137, Immunization card, Voter''s cert, SSS)"]'::jsonb, '₱200.00 (Late filing + posting fee) — pay at Municipal Treasurer', '10-12 working days (10-day posting period)', 5),
  ('nagcarlan-laguna', 'Civil Registrar', 'Certified True Copy of Civil Registry Document', 'Official certified true copy or extract of Birth, Marriage, or Death certificate on file in the local registry.', '["One (1) Valid Government ID of requester","Accomplished Request Slip (Book/Page/Registry No.)","Notarized Authorization Letter / SPA (if representative)"]'::jsonb, '₱100.00 per copy — pay at Civil Registrar / Treasurer', '1-2 working days', 6),
  ('nagcarlan-laguna', 'Civil Registrar', 'Marriage License Application', 'Application for marriage license required prior to solemnization of marriage.', '["PSA Birth Certificates of both parties","PSA CENOMAR valid within 6 months","Certificate of Pre-Marriage Counseling (PMOC) from CSWDO & Health Office","Community Tax Certificate (Cedula) of both parties","Valid IDs of both parties","Parental Consent (18-20) / Advice (21-24) if applicable"]'::jsonb, '₱200.00 – ₱300.00 — pay at Municipal Treasurer', '10-12 working days (10-day posting period)', 7),
  ('nagcarlan-laguna', 'Civil Registrar', 'Certificate of Death (Timely Registration)', 'Registration of death within 30 days of occurrence.', '["Triplicate Certificate of Death (Form 103) signed by attending physician / MHO","Valid ID of informant / nearest surviving kin","Barangay Death Certificate or Hospital Medical Record"]'::jsonb, 'Free for timely registration', 'Same day / 1 working day', 8),
  ('nagcarlan-laguna', 'Civil Registrar', 'Legitimation of Child (R.A. 9858)', 'Legal process legitimizing children born out of wedlock upon subsequent marriage of biological parents.', '["Child''s Certified Certificate of Live Birth (Local & PSA)","Parents'' Certified Marriage Contract (Local & PSA)","Joint Notarized Affidavit of Legitimation","PSA CENOMAR of both parents","Valid IDs of both parents"]'::jsonb, '₱250.00 — pay at Municipal Treasurer', '3-5 working days', 9),
  ('nagcarlan-laguna', 'Civil Registrar', 'Correction of Clerical Error (R.A. 9048 / R.A. 10172)', 'Administrative petition to correct typographical or clerical errors in birth, marriage, or death records.', '["Verified Petition Form under oath","PSA Security Paper (SECPA) copy of erroneous document","Earliest school record (Form 137 / Diploma)","Baptismal Certificate / Early church records","NBI or Police Clearance","Two (2) supporting public/private IDs/records with correct info"]'::jsonb, '₱1,000.00 (RA 9048) / ₱3,000.00 (RA 10172) — pay at Municipal Treasurer', '15-20 working days', 10),
  ('nagcarlan-laguna', 'Barangay Affairs', 'Barangay Clearance (Employment / General)', 'Barangay certification verifying that the resident has no derogatory record in the community.', '["One (1) Valid Photo ID","Community Tax Certificate (Cedula) for current year","Proof of residency (Utility bill / attestation)"]'::jsonb, '₱50.00 – ₱100.00 (Free for First-Time Jobseekers under RA 11261)', 'Same day / 1 working day', 11),
  ('nagcarlan-laguna', 'Barangay Affairs', 'Barangay Certificate of Residency', 'Certification of bona fide residency within the territorial jurisdiction of the barangay.', '["One (1) Valid ID with current address","Proof of residency (Utility bill, lease contract, or homeowner certification)"]'::jsonb, '₱50.00 — pay at Barangay Hall', 'Same day', 12),
  ('nagcarlan-laguna', 'Barangay Affairs', 'Barangay Certificate of Indigency', 'Certification of indigent status for medical, financial, educational, or legal assistance.', '["One (1) Valid ID of applicant","Proof of assistance need (Hospital bill, prescription, enrollment form, or PAO referral)"]'::jsonb, 'Free / No charge', 'Same day', 13),
  ('nagcarlan-laguna', 'Barangay Affairs', 'Barangay Business Clearance', 'Barangay-level commercial clearance required prior to Mayor''s Permit application.', '["DTI / SEC / CDA Registration Certificate","Contract of Lease or Land Title / Tax Dec","Community Tax Certificate (Cedula) of owner","Valid ID of business owner"]'::jsonb, '₱200.00 – ₱500.00 (per barangay ordinance)', '1-2 working days', 14),
  ('nagcarlan-laguna', 'Treasurer''s Office', 'Community Tax Certificate (Cedula)', 'Annual community tax certificate issued to residents and corporations upon assessment of gross income.', '["One (1) Valid Government ID","Proof of income / BIR 2316 / Payslip (for employed)"]'::jsonb, '₱5.00 basic + ₱1.00 per ₱1,000 gross earnings — pay at Treasurer', '15-30 minutes / Same day', 15),
  ('nagcarlan-laguna', 'Treasurer''s Office', 'Real Property Tax (RPT / Land Tax) Payment', 'Annual payment of ad valorem real property taxes on land, buildings, and improvements.', '["Previous Year Real Property Tax Official Receipt (OR)","Copy of Tax Declaration (TDN) from Assessor''s Office","Valid ID of owner or representative"]'::jsonb, '1% Basic RPT + 1% SEF of assessed property value', 'Same day / 1 working day', 16),
  ('nagcarlan-laguna', 'Treasurer''s Office', 'Real Property Tax Clearance', 'Certification showing all real property tax obligations on a declared property have been fully settled.', '["Official Receipts of full RPT payment for current year","Copy of Tax Declaration","Valid ID of applicant"]'::jsonb, '₱50.00 – ₱100.00 clearance fee — pay at Treasurer', '1 working day / Same day', 17),
  ('nagcarlan-laguna', 'Treasurer''s Office', 'Transfer Tax Payment & Certification', 'Tax on the sale, donation, or transfer of real property ownership.', '["Notarized Deed of Absolute Sale, Donation, or Extrajudicial Settlement","BIR Certificate Authorizing Registration (CAR) & Tax Receipts","Certified True Copy of Land Title (TCT / CCT)","Updated Tax Declaration and RPT Tax Clearance"]'::jsonb, '0.5% – 0.75% of selling price or fair market value', '1-2 working days', 18),
  ('nagcarlan-laguna', 'Assessor''s Office', 'Transfer / Issuance of Tax Declaration', 'Updating the official assessment record and issuing a new Tax Declaration under the buyer/transferee name.', '["Registered Deed of Conveyance stamped by Registry of Deeds","New Transfer Certificate of Title (TCT) under buyer''s name","BIR Certificate Authorizing Registration (CAR)","Transfer Tax Official Receipt (Treasurer)","Updated Real Property Tax Clearance (Treasurer)"]'::jsonb, '₱100.00 – ₱200.00 transfer & inspection fee — pay at Treasurer', '3-5 working days', 19),
  ('nagcarlan-laguna', 'Assessor''s Office', 'Certified True Copy of Tax Declaration', 'Official certified copy of a property''s current Tax Declaration record.', '["One (1) Valid Government ID of owner / requester","Tax Declaration Number or Property Identification Number (PIN)","Authorization Letter / SPA (if representative)"]'::jsonb, '₱50.00 – ₱100.00 per copy — pay at Treasurer', 'Same day / 1 working day', 20),
  ('nagcarlan-laguna', 'Municipal Planning and Development Office', 'Locational / Zoning Clearance', 'Certification of compliance with municipal zoning ordinances and Comprehensive Land Use Plan (CLUP).', '["Duly accomplished Locational Clearance Application Form","Certified True Copy of Land Title (TCT) or Contract of Lease","Vicinity Map and Site Development Plan signed & sealed by licensed Architect/Civil Engineer","Barangay Clearance for Construction / Business","Current Year Real Property Tax Official Receipt"]'::jsonb, 'Assessed per square meter / project cost schedule', '3-5 working days', 21),
  ('nagcarlan-laguna', 'Office of the Building Official (OBO)', 'Building Permit (New Construction / Renovation)', 'Official statutory permit to erect, alter, repair, or demolish structures under P.D. 1096.', '["Accomplished Unified Building Permit Application Forms","5 sets of complete Architectural, Structural, Electrical, Sanitary, and Mechanical Plans (signed & sealed by PRC licensed professionals with valid PTR)","Certified True Copy of Land Title (TCT) & Tax Declaration","Structural Design Computations (for buildings >2 storeys)","Bill of Materials and Cost Estimates / Specifications","Locational / Zoning Clearance (MPDO)","Fire Safety Evaluation Clearance (FSEC from BFP)","Barangay Construction Clearance"]'::jsonb, 'Assessed per NBCP Schedule of Fees — pay at Treasurer', '7-15 working days', 22),
  ('nagcarlan-laguna', 'Office of the Building Official (OBO)', 'Certificate of Occupancy', 'Authorization that a completed building structure complies with all safety codes and is fit for occupancy.', '["Accomplished Certificate of Completion Forms signed & sealed by supervising engineer","Approved Building Permit & Official Receipts","As-Built Plans (if deviations occurred)","Fire Safety Inspection Certificate for Occupancy (BFP)","Construction Logbook signed by engineer in-charge"]'::jsonb, 'Assessed based on floor area & occupancy category', '5-7 working days', 23),
  ('nagcarlan-laguna', 'Health Office', 'Sanitary Permit to Operate (Establishments)', 'Health and sanitation clearance required for commercial, food, and industrial establishments under P.D. 856.', '["Business Permit Application / Registration details","Microbiological & Physico-Chemical Water Analysis Test Results (from DOH-accredited lab)","Employee Health Certificates (Health Cards) of all staff","Pest Control Management Certification"]'::jsonb, 'Assessed by Health Office — pay at Municipal Treasurer', '2-3 working days', 24),
  ('nagcarlan-laguna', 'Health Office', 'Food Handler''s Health Certificate (Health Card)', 'Individual medical certificate certifying that food service and personal care workers are free from communicable diseases.', '["Chest X-Ray result (Normal / Clear) within last 6 months","Routine Stool Examination / Fecalysis result (Negative)","Routine Urinalysis examination result","One (1) 1x1 or 2x2 ID picture"]'::jsonb, '₱50.00 – ₱100.00 — pay at Health Office / Treasurer', '1 working day (after lab submissions)', 25),
  ('nagcarlan-laguna', 'MSWDO', 'Crisis Assistance (AICS / Financial & Medical Aid)', 'Emergency financial, hospitalization, medication, burial, or transportation assistance for indigent residents in crisis.', '["Barangay Certificate of Indigency for Financial/Medical Assistance","Valid Government ID of beneficiary and claimant","Medical Abstract / Itemized Hospital Bill / Official Prescriptions (for medical aid)","Certified Death Certificate & Funeral Contract / Statement of Account (for burial aid)"]'::jsonb, 'Free / No charge', '1-2 working days', 26),
  ('nagcarlan-laguna', 'MSWDO', 'Senior Citizen ID Registration & Booklet', 'Issuance of Senior Citizen National ID and purchase booklet for residents 60 years old and above under R.A. 9994.', '["PSA / Local Birth Certificate proving age 60+ (or valid Passport / Voter''s ID)","Barangay Certificate of Residency","Two (2) copies 1x1 recent ID photos"]'::jsonb, 'Free / No charge', 'Same day / 1-2 working days', 27),
  ('nagcarlan-laguna', 'MSWDO', 'Person with Disability (PWD) ID Application', 'Official identification card and purchase booklet for persons with permanent disabilities under R.A. 10754.', '["Medical Certificate / Disability Assessment Form signed by licensed physician","Barangay Certificate of Residency","Two (2) copies 1x1 recent ID photos","One (1) Valid ID of applicant or parent/guardian"]'::jsonb, 'Free / No charge', '1-3 working days', 28)
ON CONFLICT DO NOTHING;
